export const sample_foods = [
  {
    id: "1",
    name: "Pizza Pepperoni",
    cookTime: "10-20",
    price: 180,
    favorite: false,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "2",
    name: "Spaghetti Bolognese",
    cookTime: "20-30",
    price: 120,
    favorite: true,
    origins: ["Italy"],
    stars: 4.8,
    imageUrl: "food-2.jpg",
    tags: ["Italian", "Pasta", "Dinner"],
  },
  {
    id: "3",
    name: "Chicken Caesar Salad",
    cookTime: "15-25",
    price: 200,
    favorite: false,
    origins: ["United States"],
    stars: 4.2,
    imageUrl: "food-3.jpg",
    tags: ["Salad", "Chicken", "Lunch"],
  },
  {
    id: "4",
    name: "Sushi Rolls",
    cookTime: "25-35",
    price: 150,
    favorite: true,
    origins: ["Japan"],
    stars: 4.6,
    imageUrl: "food-4.jpg",
    tags: ["Japanese", "Sushi", "Dinner"],
  },
  {
    id: "5",
    name: "Cheeseburger",
    cookTime: "15-20",
    price: 135,
    favorite: true,
    origins: ["United States"],
    stars: 4.4,
    imageUrl: "food-5.jpg",
    tags: ["FastFood", "Burger", "Lunch"],
  },
  {
    id: "6",
    name: "Tiramisu",
    cookTime: "30-40",
    price: 220,
    favorite: false,
    origins: ["Italy"],
    stars: 4.7,
    imageUrl: "food-6.jpg",
    tags: ["Italian", "Dessert"],
  },
];

export const sample_tags = [
  { name: "All", count: 6 },
  { name: "FastFood", count: 2 },
  { name: "Italian", count: 2 },
  { name: "Dinner", count: 2 },
  { name: "Pizza", count: 1 },
  { name: "Lunch", count: 3 },
  { name: "Sushi", count: 1 },
  { name: "Dessert", count: 1 },
  { name: "Burger", count: 1 },
  { name: "Japanese", count: 1 },
];
